### ISSUE TITLE
npm: package.json missing

### ISSUE THREAD

**Issue by adamellsworth** [PabloLec/neoss#6]
from running `npm install -g neoss`

cli output
```
npm ERR! Could not install from ".nvm/versions/node/v12.22.6/lib/node_modules/neoss/src" as it does not contain a package.json file.
```

npm log
```
fetchPackageMetaData error for src@file:src Could not install from ".nvm/versions/node/v12.22.6/lib/node_modules/neoss/src" as it does not contain a package.json file.
```

**Comment by PabloLec** [comment]
Hi,

That's peculiar, as I was able to install on various distros not related to dev environment without any error.
Anyway, that was probably caused by a line in `package.json` which was an artifact from previous imports configuration.

I removed that line, so this problem should be fixed.
Please try to install new version `npm install -g neoss@1.1.3`. Let me know if it fixed it. :wink:

**Comment by adamellsworth** [comment]
resolved. Ty
